USE [master]
GO

/****** Object:  Database [BD_Biblioteca]    Script Date: 02/08/2023 12:20:12 ******/
DROP DATABASE [BD_Teste]
GO

/****** Object:  Database [BD_Biblioteca]    Script Date: 02/08/2023 12:20:12 ******/
CREATE DATABASE [BD_Teste]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_Teste', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BD_Teste.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_Teste_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BD_Teste_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Teste].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_Biblioteca] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BD_Biblioteca] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_Teste] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_Biblioteca] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_ Biblioteca] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BD_Biblioteca] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_Biblioteca] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BD_Biblioteca] SET  MULTI_USER 
GO

ALTER DATABASE [BD_Biblioteca] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_Biblioteca] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_Biblioteca] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_Biblioteca] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BD_Biblioteca] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_Biblioteca] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BD_Biblioteca] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BD_Biblioteca] SET  READ_WRITE 
GO

